// LOCALHOST
GET http://localhost:8080/contacts 
###
POST http://localhost:8080/contacts HTTP/1.1 
content-type: application/json

{
    "firstName":"Ryan",
    "lastName":"Reynolds",
    "email":"reynoldsr@contact.com",
    "favoriteColor":"red",
    "birthday":"04/14/2014"
}
###
GET http://localhost:8080/contacts/65b5cbd6c3c1594787c71133
### 
PUT http://localhost:8080/contacts/65b5cbd6c3c1594787c71133 HTTP/1.1 
content-type: application/json

{
    "firstName":"Thomas",
    "lastName":"Brodie-Sangster",
    "email":"brodiet@contact.com",
    "favoriteColor":"green",
    "birthday":"01/21/2011"
}
###
DELETE http://localhost:8080/contacts/65bc8afb5a0d114a5a9ee969 HTTP/1.1
###
// RENDER
GET http://nelson-austin.onrender.com/contacts 
###
POST http://nelson-austin.onrender.com/contacts HTTP/1.1 
content-type: application/json

{
    "firstName":"Ryan",
    "lastName":"Reynolds",
    "email":"reynoldsr@contact.com",
    "favoriteColor":"red",
    "birthday":"04/14/2014"
}
###
GET http://nelson-austin.onrender.com/contacts/65b5cbd6c3c1594787c71133
### 
PUT http://nelson-austin.onrender.com/contacts/65b5cbd6c3c1594787c71133 HTTP/1.1 
content-type: application/json

{
    "firstName":"Thomas",
    "lastName":"Brodie-Sangster",
    "email":"brodiet@contact.com",
    "favoriteColor":"green",
    "birthday":"01/11/2011"
}
###
DELETE http://nelson-austin.onrender.com/contacts/65bc8b9c5a0d114a5a9ee96a HTTP/1.1
###